# Generated by Django 5.1.6 on 2025-02-13 15:47

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birthDate', models.DateField(null=True)),
                ('height', models.FloatField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('mobileNumber', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200, null=True)),
                ('membershipType', models.CharField(max_length=15)),
                ('sex', models.CharField(default='NA', max_length=30)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ValidationSession',
            fields=[
                ('validationCode', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('expirationDate', models.DateField(null=True, verbose_name='Expiration Date')),
            ],
        ),
        migrations.CreateModel(
            name='DailyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(auto_now_add=True)),
                ('member', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='account.member')),
            ],
            options={
                'ordering': ['startDate'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(auto_now_add=True)),
                ('expirationDate', models.DateField(default=django.utils.timezone.now)),
                ('member', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='account.member')),
            ],
            options={
                'ordering': ['startDate'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('expirationDate', models.DateField(null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.member')),
            ],
        ),
    ]
