# Generated by Django 5.1.6 on 2025-02-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_delete_refreshtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mobileNumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
