# Generated by Django 5.1.6 on 2025-02-23 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_member_mobilenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_trainer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.member'),
        ),
    ]
