# Generated by Django 5.1.6 on 2025-02-23 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_trainer_remove_member_is_trainer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gymTrainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.trainer'),
        ),
    ]
