# Generated by Django 5.1.6 on 2025-02-23 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_member_options_alter_trainer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gymTrainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.trainer'),
        ),
    ]
