# Generated by Django 5.1.6 on 2025-03-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_membercheckout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membercheckout',
            name='id',
        ),
        migrations.AlterField(
            model_name='membercheckout',
            name='checkoutId',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
