# Generated by Django 5.1.6 on 2025-03-07 09:34

import account.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_membercheckout_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='user_ptr',
        ),
        migrations.AlterField(
            model_name='member',
            name='gymTrainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.member'),
        ),
        migrations.AddField(
            model_name='member',
            name='facebookAccount',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='is_trainer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.userProfilePath),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobileNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
