# Generated by Django 5.1.6 on 2025-03-10 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_delete_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='membercheckout',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='membercheckout',
            name='type',
            field=models.CharField(default='membership', max_length=100),
            preserve_default=False,
        ),
    ]
