# Generated by Django 5.1.6 on 2025-03-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_membercheckout_date_membercheckout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='membercheckout',
            name='price',
            field=models.FloatField(default=1000.0),
            preserve_default=False,
        ),
    ]
