# Generated by Django 5.1.7 on 2025-06-03 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_membercheckout_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membercheckout',
            name='date',
        ),
        migrations.RemoveField(
            model_name='membercheckout',
            name='price',
        ),
        migrations.RemoveField(
            model_name='membercheckout',
            name='type',
        ),
    ]
