# Generated by Django 5.1.7 on 2025-06-17 03:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_membercheckout_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subscription', models.BooleanField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='monthlymembership',
            name='member',
        ),
        migrations.RemoveField(
            model_name='member',
            name='membershipType',
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(auto_now_add=True)),
                ('expirationDate', models.DateField(default=django.utils.timezone.now)),
                ('member', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='account.member')),
                ('membershipType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.membershiptype')),
            ],
            options={
                'ordering': ['startDate'],
            },
        ),
        migrations.DeleteModel(
            name='DailyMembership',
        ),
        migrations.DeleteModel(
            name='MonthlyMembership',
        ),
    ]
