# Generated by Django 5.1.5 on 2025-02-03 18:04

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membershipType', models.CharField(max_length=30)),
                ('startDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationSession',
            fields=[
                ('validationCode', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('dueDate', models.DateField(default=datetime.date(2025, 2, 5))),
            ],
        ),
        migrations.CreateModel(
            name='DailyMembership',
            fields=[
                ('membership_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gym.membership')),
                ('price', models.FloatField(default=50.0)),
            ],
            bases=('gym.membership',),
        ),
        migrations.CreateModel(
            name='MonthlyMembership',
            fields=[
                ('membership_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gym.membership')),
                ('dueDate', models.DateField(default=datetime.date(2025, 3, 6))),
                ('price', models.FloatField(default=1000.0)),
            ],
            bases=('gym.membership',),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('mobileNumber', models.CharField(max_length=10)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gym.membership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('expirationDate', models.DateField(default=datetime.date(2025, 2, 11))),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
