# Generated by Django 5.1.6 on 2025-03-07 09:34

import django.db.models.deletion
import django.utils.timezone
import gym.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_trainer_user_ptr_alter_member_gymtrainer_and_more'),
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramWorkoutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('details', models.JSONField()),
                ('programWorkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.programworkout')),
            ],
        ),
        migrations.CreateModel(
            name='TimelineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=gym.models.timelineRecordPath)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.member')),
            ],
        ),
    ]
