# Generated by Django 5.1.6 on 2025-03-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_programworkoutrecord_timelinerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='distance',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='reps',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='sets',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='time',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='weight',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
