# Generated by Django 5.1.6 on 2025-03-03 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calorie', models.FloatField()),
                ('protein', models.FloatField()),
                ('carb', models.FloatField()),
                ('fat', models.FloatField()),
                ('mealType', models.CharField(choices=[('BF', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('S', 'Snacks')], max_length=5)),
                ('bodyGoal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi', models.CharField(choices=[('UW', 'Under Weight'), ('HW', 'Healthy Weight'), ('OW', 'Over Weight'), ('O', 'Obese')], max_length=15)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietary.meal')),
            ],
        ),
    ]
