# Generated by Django 5.1.6 on 2025-02-13 15:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('timeIn', models.TimeField(default=django.utils.timezone.now)),
                ('timeOut', models.TimeField(null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.member')),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('content', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('expirationDate', models.DateField(null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.member')),
            ],
        ),
    ]
