# Generated by Django 5.1.6 on 2025-05-20 21:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_qrcode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='timeOut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='expirationDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
